# Generated by Django 5.0 on 2024-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinlib', '0009_prediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
